# docker-compose exec web sh
version: "3.3"
services:
    web:
        build: .
        ports:
            - "4567:4567"
        volumes:
            - .:/code
        environment:
            ATTEST_APPID: "XXXXXXXXXX.io.github.kwrsin.Exp-Artest"
