# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem "sinatra-contrib"
gem "cbor"

group :development do
  gem 'guard'
  gem 'guard-shell'
end

group :test do
    gem 'test-unit'
    gem 'jwt'
    gem 'rake'
end
