require 'rake/testtask'

task default: [:guard]

Rake::TestTask.new do |test|
    `./runtest.sh`
    test.test_files = Dir[
        './tests/unitStrageManagerTest.rb',
    ]
    test.verbose = true
end

task :guard do
    sh 'bundle exec guard start'
end